apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: controller-manager
  namespace: actions-runner-system
spec:
  encryptedData:
    github_app_id: <REPLACE_WITH_CIPHERTEXT>
    github_app_installation_id: <REPLACE_WITH_CIPHERTEXT>
    github_app_private_key: <REPLACE_WITH_CIPHERTEXT>
  template:
    metadata:
      name: controller-manager
      namespace: actions-runner-system
    type: Opaque
