apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gh-actions-runner-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"  
spec:
  project: infra
  destination:
    server: https://kubernetes.default.svc
    namespace: gh-actions-runner-system-infra
  source:
    repoURL: https://actions-runner-controller.github.io/actions-runner-controller
    chart: actions-runner-controller
    targetRevision: 0.23.7
    helm:
      values: |
        authSecret:
          create: false
          name: gh-actions-controller-manager
        githubWebhookServer:
          enabled: false
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/preserveUnknownFields
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true   # <- isto resolve o limite de anotação
      - RespectIgnoreDifferences=true   # por si tu versión requiere habilitarlo
