apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: liqprog-dev
  namespace: argocd
spec:
  project: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: liqprog-dev
  sources:
    # Source 1: Kustomize overlay (applies Secret first)
    - repoURL: git@github.com:jvizueta/k8s-apps-private.git
      targetRevision: main
      path: liqprog/mysql/overlays/dev
      ref: values     # <-- alias so Helm can reference files from here
      kustomize: {}

    # Source 2: Helm (Bitnami MySQL) consuming that values.yaml
    - repoURL: https://charts.bitnami.com/bitnami
      chart: mysql
      targetRevision: 14.0.3
      helm:
        releaseName: liqprog-mysql
        valueFiles:
          - $values/liqprog/mysql/overlays/dev/values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
