apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-core
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: core
  sources:
    - chart: longhorn
      repoURL: https://charts.longhorn.io
      targetRevision: v1.9.1 # Replace with the Longhorn version you'd like to install or upgrade to
      helm:
        values: |
          # DEV overrides
          # Desactiva el hook pre-upºgrade SOLO para instalación inicial con ArgoCD.
          # Vuelve a activarlo antes de subir de versión.
          preUpgradeChecker:
            jobEnabled: false
            
          persistence:
            defaultClass: false
            reclaimPolicy: Retain
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system